CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE book (id SERIAL PRIMARY KEY, author VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL);
ALTER TABLE book ADD CONSTRAINT book_title_uk UNIQUE (title);
